version: "3.2"
services:
  php:
    build: './php/'
    container_name: sina_php
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    build: './apache/'
    container_name: sina_apache
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80" # Debe ser 80 para poder añadir una entrada en localhost que apunte a www.asociacionsina.org
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql:5.7
    # OJO: Esto habrá que cambiarlo para hacer un build y poner la configuración de mysql correcta
    # build: './mysql/'
    container_name: sina_mysql
    networks:
      - backend
    environment:
      #- MYSQL_DATABASE=db
      #- MYSQL_USER=user
      #- MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sina_phpmyadmin
    networks:
      - backend    
    depends_on:
      - mysql
    environment:
     # - PMA_ARBITRARY=1 # Descomentar esto y comentar el resto para conectar a otros servidores
     - PMA_USER=root
     - PMA_PASSWORD=rootpassword
     - PMA_HOST=mysql
    restart: always
    ports:
     - 9090:80
    volumes:
     - /sessions      
networks:
  frontend:
  backend:
