# https://hub.docker.com/r/phpmyadmin/phpmyadmin/
FROM phpmyadmin/phpmyadmin

# Incrementar tamaño de upload para volcar la BD
COPY increase_upload_size.ini /usr/local/etc/php/conf.d/increase_upload_size.ini

